import { Company } from "./company.model";

export interface News {
    id?: number; // Optional for new inserts
    company_id: number;
    headline: string;
    sector: string;
    sentiment: boolean;
    created_at?: Date; // Auto-generated by Supabase
    company?: Company; // Include full company data when fetching

}
