import { Company } from "./company.model";

export interface Trade {
    id?: number; // Optional for new inserts
    company_id: number;
    type: string;
    closed_date: Date;
    upload_date: Date;
    currency: string;
    volume: number;
    created_at?: Date; // Auto-generated by Supabase
    company?: Company;

}
